Callback_url = "https://example.com"
Payloads = "./payloads.txt"
Headers = "./headers.txt"
Parameters = "./parameters.txt"
Extensions = ".webm, .ttf, .svg, .gif, .png, .js, .woff, .woff2, .jpeg, .jpg, .css, .ico, .m3u8, .ts, .bmp"
